services:
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "allkeys-lru"]

  mcs-scenario-checker-for-maker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis